crop_name = str(input("Crop:"))
avg_water_rai = float(input("Estimated annual water consumption (L/rai):"))
planting_area = float(input("Nation-wide growing area (rai):"))
avg_crop_yield = float(input("Average crop yield per growing area (kg/rai):"))
whole_sale_price = float(input("Estimated wholesale price (baht/kg):"))
print("\n")
print("{} over {:,} rai".format(crop_name.upper(), int(planting_area))) 
print("Total water usage: {:,.2f} ML".format(avg_water_rai * planting_area / 1000000))
print("Total crop yield: {:,.2f} kg or {:,.2f} ton ".format(planting_area * avg_crop_yield, planting_area * avg_crop_yield / 1000)) 
print ("Total earning: {:,.2f} mil. baht".format(whole_sale_price * avg_crop_yield * planting_area / 1000000))
print ("Average crop yield per water usage: {:,.6f} kg/L".format((avg_crop_yield * planting_area)/(planting_area * avg_water_rai))) 
print ("Average earning per water usage: {:,.6f} baht/L".format((avg_crop_yield * planting_area * whole_sale_price) / (avg_water_rai * planting_area) ))
print ("Average earning per area: {:,.2f} baht/rai".format((avg_crop_yield * planting_area * whole_sale_price)/(planting_area)))